# Problem 1 

In [6]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([3,5,6,8,2])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)

[2 3 5 6 8]


# Problem 2

In [48]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10,15,30,45,60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
print(np.arange(5,15))
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

print(np.arange(50,100,5))
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
print(np.zeros(10))

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print(np.ones(10))

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
print(np.arange(0,100,20))

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

print(np.random.randint(10,30,5))
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
print(np.random.randint(-1,1,10))

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
print(np.random.randint(10,50, size =(3,5)))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
z = np.arange(10,20,1) 
print(z[0])
print(z[1])
print(z[2])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
s = np.random.randint(10,50, size =(3,5))
print(s[-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
s = np.random.randint(10,50, size =(3,5) )
print(s[0, :])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(s[2,3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0 20 40 60 80]
[27 16 12 28 19]
[-1 -1 -1  0  0 -1 -1  0  0 -1]
[[34 17 36 38 33]
 [28 17 49 18 41]
 [21 12 10 16 13]]
10
11
12
[44 42 22 33 12]
[36 33 48 30 43]
36
