# Problem 1

In [21]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.array([2,4,5,7,9])

# 3 - matris'in boyutunu öğrenin
print(a.shape)

# 4 - matris'i yeniden boyutlandırın
a = np.array([2,4,5,7,9])
x = a.reshape([5,1])
print(x)

# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)


(5,)
[[2]
 [4]
 [5]
 [7]
 [9]]
1


# Problem 2

In [43]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
tek = np.array([1,3,5,7,9])

# 2 - Oluşturduğunuz matrisi parçalayın
ayır = np.split(tek, [2,3])
print(ayır)

# 3 - Parçalanmış matrisleri birleştirin

print(np.concatenate(ayır))


[array([1, 3]), array([5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [61]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
aralık = np.arange(5,101,2)

aralik2 = np.random.choice(aralık,size = 10)
print(aralik2)

# 2 - matris'in özelliklerini inceleyin
print(aralik2.ndim)
print(aralik2.shape)
print(aralik2.size)
print(aralik2.dtype)

[99 35  9 93 15 67 63 49 35 69]
1
(10,)
10
int64
