In [1]:
#numpy listelerden daha verimli veri saklıyor. 
#klasik yöntem
a = [1,2,3,4,5]
b = [2,3,4,5,6]
ab = []
for i in range(0,len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20, 30]


In [3]:
#numpy ile
import numpy as np
a = np.array([1,2,3,4,])
b = np.array([2,3,4,5])
print(a*b)


[ 2  6 12 20]


In [4]:
#reshape() arreylerin boyutlarını değiştiriyorsun.
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#shape() arreylerin boyutlarını öğrenirsin
print(multi.shape)

(3, 3)


In [ ]:
#ndim() areylerin boyut sayısını öğreniriz.

In [7]:
#concantenate() numpy arreylerini birleştirmek için kullanılır. 
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,3])
print(np.concatenate([x,y]))

[1 2 3 4 5 6 7 8 9 3]


In [8]:
z = np.array([11,23,4,6,7,4,5,7,875,3393])
print(np.concatenate([x,y,z]))

[   1    2    3    4    5    6    7    8    9    3   11   23    4    6
    7    4    5    7  875 3393]


In [ ]:
#axis = 0 satır bazında birleştirme
#axis = 1 sütın bazında birleştirme

In [11]:
#split() array ayırma yapıyosun
#vsplit() yatau ayırma 
#hsplit() dikey ayırma
#np.arange() belli bir aralıkta sayıları oluşturmak için
#np.zeros() 0 lardan oluşan bir numpy dizisi oluşturur.
np.zeros(5)
#np.ones 1lerden oluşan
np.ones(4)
 

array([1., 1., 1., 1.])

In [14]:
#np.linspace()belli bir aralıkta sayı oluşturmak için
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [15]:
#rastagele oluşturur
np.random.randint(2,50,3)

array([10, 41, 34], dtype=int32)

In [16]:
#ORTAK ÖZELLİKLER
#ndim=boyut sayısı
##shape=boyut bilgisi
###size=toplam eleman sayısı
####dtype=veri tipi
a = np.random.randint(5,size = 30)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(30,)
30
int32


In [18]:
#sorting() array sıralama 
v = np.array([4,54,6,9,56,7654])

v.sort()
print(v)

[   4    6    9   54   56 7654]


In [23]:
#index ile elemanlara erişebilirsin
a = np.random.randint(10,size = 10)
print(a[0])

7


In [24]:
x = np.random.randint(10,size = (2,9))
print(x)

[[6 9 2 8 7 4 5 6 2]
 [8 7 6 9 8 4 6 0 9]]


In [26]:
print(x[1,2])

6


In [27]:
x[1,4] = 100
print(x)

[[  6   9   2   8   7   4   5   6   2]
 [  8   7   6   9 100   4   6   0   9]]


In [29]:
#slicing( array alt kümesine erişmek)
a = np.arange(20,30)

In [30]:
print(a[0:])

[20 21 22 23 24 25 26 27 28 29]


In [31]:
print(a[1::3])

[21 24 27]


In [32]:
b = np.random.randint(10,size = [6,9])
print(b)

[[8 1 7 2 4 6 0 2 9]
 [7 9 8 6 4 1 4 4 2]
 [0 3 3 9 9 1 8 1 0]
 [0 1 8 9 1 1 8 9 1]
 [4 6 6 1 4 7 9 5 5]
 [3 7 9 5 2 8 4 1 1]]


In [33]:
print(b[:,0])

[8 7 0 0 4 3]


In [ ]:
#fancy index anlamadım.

In [34]:
#koşullu eleman işlemleri
v = np.array([4,5,6,28,9])
print(v>5)

[False False  True  True  True]


In [35]:
print(v[v<3])

[]


In [ ]:
#substract her birinden çıkarma işlemi yapıyor
#add ekleme yapıyor np.add(v,2)
#multiply çarpma işlemi
#divide bölme yapar
#np.power(v,2) üs alıyor
#absolute mutlak değer alıyor


In [36]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
